export const SET_INFO_MESSAGE = 'SET_INFO_MESSAGE'
export const INPUT_CHANGE = 'INPUT_CHANGE'
export const RESET_FORM = 'RESET_FORM'
export const SET_IS_FETCHING = "SET_IS_FETCHING"
export const SET_ERROR = "SET_ERROR"
export const RESET_SELECTED_STATE = "RESET_SELECTED_STATE "
export const CLEAR_INFO_MESSAGE = "CLEAR_INFO_MESSAGE"
